### PR TITLE
286: added filesystem command timeout

### LINKED ISSUE #286: [BUG] Filesystem fetcher HANG
**Describe the bug**
When an NFS filesystem is present on the database server and it doesn't respond the filesytem fetcher hangs and doesn't allow ercole-agent to finish execution

**Expected behavior**
If the filesystem fetcher does not respond in 20 seconds it is automatically killed, the filesystem information will be set empty and ercole-agent go ahead working anyway.

**To Reproduce**
1. Mount an NFS on a server
2. Shut down the machine exporting the NFS
3. run ercole-agent

### PR DESCRIPTION
**Pull request by afumagalli98**
Fix #286

### CODE REVIEW

**Comment by amreo** [comment]
Wasn't it more easier to implement the feature with the timeout(1) program instead of implementing it at go level?
https://www.man7.org/linux/man-pages/man1/timeout.1.html

**Review by cirelli94 — CHANGES_REQUESTED** [review]
Please create a function to enable this feature

**Comment by cirelli94** [comment]
> Wasn't it more easier to implement the feature with the timeout(1) program instead of implementing it at go level?
Yes, it would be easier but we decided to implement it in `go` side because we think others fetchers will need this too.
We are thinking to add the same functionality to all others fetchers but with an high timeout, like 24h, to avoid any fetchers to stop an agent execution permanently!

**Comment by cirelli94** [comment]
> Wasn't it more easier to implement the feature with the timeout(1) program instead of implementing it at go level? https://www.man7.org/linux/man-pages/man1/timeout.1.html

Yes, it would be easier but we decided to implement it in `go` side because we think others fetchers will need this too.
We are thinking to add the same functionality to all others fetchers but with an high timeout, like 24h, to avoid any fetchers to stop an agent execution permanently!

**Comment by cirelli94** [comment]
I added https://github.com/ercole-io/ercole-agent/issues/290 for generic deadline, so this PR must relate strictly the filesystem fetcher, thanks.

**Review by cirelli94 — APPROVED** [review]

**Pull request merged**
