### PR TITLE
Ignore errors from fetcher service

### LINKED ISSUE #295: [BUG] Ignore errors from fetcher services.sh
If the fetcher services.sh raises an error you have to ignore it and go on with the process, add errors and finally show database section.

The problem is show database section that doesn't work.

It is not correct view only host section:

image

### PR DESCRIPTION
**Pull request by cbiglioli**
Fix #295 Ignore errors from fetcher service

### CODE REVIEW

**Review by cirelli94 — CHANGES_REQUESTED** [review]
Don't use `strings.Contains` to check errors, there is `errors.Is` check and `%w` unwrap methods!
https://go.dev/blog/go1.13-errors

OK!

I think there is already the error management done [here](https://github.com/cbiglioli/ercole-agent/blob/f34850253f847cfa2a22ce5868521a92a0505f62/builder/common_builder/oracle_databases.go#L277
); this is not needed at all or done in the wrong place, let me know what do you think!

Yes, I agree with you that there is the error management for Services errors and in this case Services will be:
`database.Services = []model.OracleDatabaseService{}`

But we have another problem: if there is a Services error, all databases information will be null (getOracleDBs function):


for i := range oratabEntries {
		entry := oratabEntries[i]
		utils.RunRoutine(b.configuration, func() {
			b.log.Debugf("oratab entry: [%v]", entry)
			database, err := b.getOracleDB(entry, host, hostCoreFactor)
			if err != nil {
				b.log.Errorf("Can't get Oracle db: %s\n Errors: %s\n", entry, err)
				errChan <- err
				**databaseChan <- nil**
	
				return
			}

			databaseChan <- database
		})
	}

This is not correct, only Services information must be null, not all databases information.

**Comment by cbiglioli** [comment]
> Don't use `strings.Contains` to check errors, there is `errors.Is` check and `%w` unwrap methods! https://go.dev/blog/go1.13-errors

OK!

> I think there is already the error management done [here](https://github.com/cbiglioli/ercole-agent/blob/f34850253f847cfa2a22ce5868521a92a0505f62/builder/common_builder/oracle_databases.go#L277); this is not needed at all or done in the wrong place, let me know what do you think!

Yes, I agree with you that there is the error management for Services errors and in this case Services will be:
`database.Services = []model.OracleDatabaseService{}`

But we have another problem: if there is a Services error, all databases information will be null (getOracleDBs function):



for i := range oratabEntries {

		entry := oratabEntries[i]

		utils.RunRoutine(b.configuration, func() {
			b.log.Debugf("oratab entry: [%v]", entry)
			database, err := b.getOracleDB(entry, host, hostCoreFactor)
			if err != nil {
				b.log.Errorf("Can't get Oracle db: %s\n Errors: %s\n", entry, err)
				errChan <- err
			       databaseChan <- nil
	
				return
			}

			databaseChan <- database
		})
	}

This is not correct, only Services information must be null, not all databases information --> `databaseChan <- nil`.

**Comment by cirelli94** [comment]
Thanks, we have just find out a wrong behaviour! That's a bug this PR must depends on!
https://github.com/ercole-io/ercole-agent/issues/318

**Comment by cirelli94** [comment]
Please, convert this PR in a draft until that bug will be fixed, than we will reopen it.

**Review by cirelli94 — APPROVED** [review]

**Pull request merged**
