### PR TITLE
Added support to custom fetchers + fix rolling

### PR DESCRIPTION
**Pull request by amreo**
Fixes https://github.com/ercole-io/ercole/issues/426
Also fixes a 422 when the version is rolling.

### CODE REVIEW

**Comment by cirelli94** [comment]
There are no test.
Would you mind to add some tests?

**Comment by amreo** [comment]
Mhm OK

**Comment by cirelli94** [comment]
It would be GREAT to have some valgrind-like tests!

**Comment by amreo** [comment]
Mhmh valgrind-like? examples? links?

**Comment by amreo** [comment]
Mhm what can be easely tested?

**Pull request closed without merging**
