### PR TITLE
Fixed check directory is writable

### PR DESCRIPTION
**Pull request by cirelli94**
There was an useless check that the current user was the owner of the directory.
This wasn't needed, only write and execute permission bits are.

### CODE REVIEW

**Comment by amreo** [comment]
What is a check directory?

**Comment by cirelli94** [comment]
> What is a check directory?

the check of a directory to be writable!
It's an action, not "a thing"

**Comment by amreo** [comment]
I tough you need a writable directory to put temporary files for fetchers, that it is not a good thing.

**Comment by cirelli94** [comment]
No no, we are using this directory for the logs.
https://github.com/ercole-io/ercole-agent/blob/a9fdf7274a2984ffd303813e480fc7888d10ee00/config/config.go#L175

**Comment by amreo** [comment]
But it wasn't simpler to use journalctl/systemd features for the logs?

**Comment by cirelli94** [comment]
As stated in that stackexchange answer, that is only supported from recent systemd versions, so we would have a lot of problems in production.
Even edit each systemd file manually at each installation is a huge and prone to errors task!
I would have liked it too, but finally I thought it's not the best solution.

**Pull request merged**
